export const platformState = {
  currentUserId: 'u-admin',
  users: [
    {
      id: 'u-admin',
      name: 'Admin Nexora',
      role: 'SUPER_ADMIN',
      phone: '+243 971 037 431',
      email: 'admin@nexora.com',
      city: 'Kinshasa',
      kycStatus: 'VERIFIED',
      walletBalance: 0,
      status: 'ACTIVE',
      active: true,
      avatarUrl: '',
      companyName: 'Nexora',
      address: 'Kinshasa',
      availableBalance: 0,
      blockedBalance: 0,
    },
    {
      id: 'u-supplier-1',
      name: 'Nexora Industrial Supply',
      role: 'FOURNISSEUR',
      phone: '+243 840 000 501',
      email: 'supplier@nexora.com',
      city: 'Kinshasa',
      kycStatus: 'VERIFIED',
      walletBalance: 0,
      status: 'ACTIVE',
      sellerStatus: 'VERIFIED',
      supplierLevel: 'GOLD',
      companyName: 'Nexora Industrial Supply',
      address: 'Gombe, Kinshasa',
      availableBalance: 0,
      blockedBalance: 0,
      active: true,
    },
  ],
  shops: [
    {
      id: 'shop-industrial',
      sellerId: 'u-supplier-1',
      name: 'Nexora Industrial Supply',
      slug: 'nexora-industrial-supply',
      description: 'Verified supplier for electronics, energy, telecom and business equipment.',
      phone: '+243 840 000 501',
      address: 'Gombe, Kinshasa',
      city: 'Kinshasa',
      openingHours: '08:00 - 18:00',
      rating: 4.8,
      status: 'APPROVED',
    },
  ],
  commissionRules: [
    { id: 'cr-market', scope: 'Marketplace', target: 'All products', city: 'ALL', rate: 8 },
    { id: 'cr-logistics', scope: 'Service', target: 'Logistics', city: 'ALL', rate: 12 },
  ],
  products: [
    {
      id: 'prod-phone-pro',
      sellerId: 'u-supplier-1',
      shopId: 'shop-industrial',
      name: '5G Business Smartphone',
      sku: 'NX-PHONE-5G-001',
      category: 'Telephones',
      city: 'Kinshasa',
      subcategory: 'Mobile devices',
      condition: 'New',
      pickupAddress: 'Gombe, Kinshasa',
      price: 148,
      promoPrice: 139,
      stock: 240,
      sponsored: true,
      rating: 4.8,
      status: 'APPROVED',
      rejectionReason: '',
      commissionRate: 8,
      moq: 20,
      wholesalePrice: 119,
      leadTime: '5-7 days',
      b2bEnabled: true,
      origin: 'RDC',
      certifications: ['Verified supplier', 'Warranty'],
      imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80',
      minOrderValue: 2380,
      tradeAssurance: true,
    },
    {
      id: 'prod-solar-kit',
      sellerId: 'u-supplier-1',
      shopId: 'shop-industrial',
      name: 'Commercial Solar Energy Kit',
      sku: 'NX-SOLAR-002',
      category: 'Electronique',
      city: 'Kinshasa',
      subcategory: 'Energy',
      condition: 'New',
      pickupAddress: 'Gombe, Kinshasa',
      price: 420,
      promoPrice: 0,
      stock: 85,
      sponsored: true,
      rating: 4.9,
      status: 'APPROVED',
      rejectionReason: '',
      commissionRate: 10,
      moq: 5,
      wholesalePrice: 365,
      leadTime: '10 days',
      b2bEnabled: true,
      origin: 'RDC',
      certifications: ['Installation support', 'Warranty'],
      imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80',
      minOrderValue: 1825,
      tradeAssurance: true,
    },
    {
      id: 'prod-router',
      sellerId: 'u-supplier-1',
      shopId: 'shop-industrial',
      name: 'Enterprise Wi-Fi 6 Router',
      sku: 'NX-NET-003',
      category: 'Informatique',
      city: 'Kinshasa',
      subcategory: 'Networking',
      condition: 'New',
      pickupAddress: 'Gombe, Kinshasa',
      price: 96,
      promoPrice: 0,
      stock: 150,
      sponsored: false,
      rating: 4.6,
      status: 'APPROVED',
      rejectionReason: '',
      commissionRate: 8,
      moq: 10,
      wholesalePrice: 78,
      leadTime: '3-5 days',
      b2bEnabled: true,
      origin: 'RDC',
      certifications: ['Verified supplier'],
      imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
      minOrderValue: 780,
      tradeAssurance: true,
    },
  ],
  orders: [],
  rides: [],
  deliveries: [],
  software: [],
  cloudRequests: [],
  kyc: [],
  transactions: [],
  withdrawals: [],
  disputes: [],
  messages: [],
  notifications: [],
  auditLogs: [],
  rfqs: [
    {
      id: 'rfq-business-phones',
      buyerId: 'u-admin',
      title: 'Need 300 smartphones for business distribution',
      category: 'Telephones',
      city: 'Kinshasa',
      quantity: 300,
      targetPrice: 115,
      deliveryDeadline: '14 days',
      notes: 'Business smartphones with warranty, packaging and delivery terms.',
      status: 'OPEN',
      createdAt: new Date().toISOString(),
    },
  ],
  quotes: [],
  favorites: [],
};
